name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create required directories
        run: |
          mkdir -p test-music
          mkdir -p music
          chmod 755 test-music music

      - name: Run unit tests
        run: mvn clean test -Dspring.profiles.active=test
        env:
          JWT_SECRET: testSecretKeyForCIEnvironment123456789012345678901234567890
          SPRING_PROFILES_ACTIVE: test

      - name: Generate coverage report
        if: success()
        run: |
          ./mvnw jacoco:report
          echo "Coverage report generated in target/site/jacoco/"

      - name: Upload coverage reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: target/site/jacoco/

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package -DskipTests