name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Create required directories
        run: |
          mkdir -p test-music
          mkdir -p music
          chmod 755 test-music music

      - name: Run unit tests
        run: ./mvnw clean test -Dspring.profiles.active=test
        env:
          JWT_SECRET: testSecretKeyForCIEnvironment123456789012345678901234567890
          SPRING_PROFILES_ACTIVE: test

      - name: Show test results
        if: always()
        run: |
          echo "=== TEST RESULTS SUMMARY ==="
          if [ -d "target/surefire-reports" ]; then
            echo "Test reports found:"
            find target/surefire-reports -name "*.xml" -exec basename {} \; | head -10
          
            # Count tests
            if [ -f target/surefire-reports/TEST-*.xml ]; then
              TESTS=$(grep -h 'testcase' target/surefire-reports/TEST-*.xml | wc -l || echo "0")
              FAILURES=$(grep -h 'failure\|error' target/surefire-reports/TEST-*.xml | wc -l || echo "0")
              echo "Total tests: $TESTS"
              echo "Failures: $FAILURES"
          
              if [ "$FAILURES" -eq 0 ]; then
                echo "All tests passed!"
              else
                echo "Some tests failed"
              fi
            fi
          else
            echo "No test reports found"
          fi

      - name: Generate coverage report
        if: success()
        run: |
          ./mvnw jacoco:report
          echo "Coverage report generated in target/site/jacoco/"

      - name: Upload test and coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage-reports-${{ github.run_number }}
          path: |
            target/surefire-reports/
            target/site/jacoco/
          retention-days: 7
          if-no-files-found: warn

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_number }}
          path: target/*.jar
          retention-days: 7